portal:
  image: nginx
  ports:
   - "80:80"
  volumes:
   - ./cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcatOne:tomcat1
   - tomcatTwo:tomcat2
   - tomcatThree:tomcat3
tomcatOne:
  image: tomcat:7.0-jre8
  volumes:
   - ./cluster/hazelcast-server.xml:/usr/local/tomcat/conf/server.xml
   - ./cluster/hazelcast-context.xml:/usr/local/tomcat/conf/context.xml
   - ./cluster/lib/hazelcast-tomcat7-sessionmanager-1.1.3.jar:/usr/local/tomcat/lib/hazelcast-tomcat7-sessionmanager-1.1.3.jar
   # - ~/.m2/repository/com/hazelcast/hazelcast-tomcat7-sessionmanager/1.1.4-SNAPSHOT/hazelcast-tomcat7-sessionmanager-1.1.4-SNAPSHOT.jar:/usr/local/tomcat/lib/hazelcast-tomcat7-sessionmanager-1.1.4-SNAPSHOT.jar
   - ./cluster/lib/hazelcast-all-3.9.1.jar:/usr/local/tomcat/lib/hazelcast-all-3.9.1.jar
   - ./test-app/target/basic-web-app:/usr/local/tomcat/webapps/ROOT
   - ./cluster/logging.properties:/usr/local/tomcat/conf/logging.properties
tomcatTwo:
  image: tomcat:7.0-jre8
  volumes:
   - ./cluster/hazelcast-server.xml:/usr/local/tomcat/conf/server.xml
   - ./cluster/hazelcast-context.xml:/usr/local/tomcat/conf/context.xml
   - ./cluster/lib/hazelcast-tomcat7-sessionmanager-1.1.3.jar:/usr/local/tomcat/lib/hazelcast-tomcat7-sessionmanager-1.1.3.jar
   # - ~/.m2/repository/com/hazelcast/hazelcast-tomcat7-sessionmanager/1.1.4-SNAPSHOT/hazelcast-tomcat7-sessionmanager-1.1.4-SNAPSHOT.jar:/usr/local/tomcat/lib/hazelcast-tomcat7-sessionmanager-1.1.4-SNAPSHOT.jar
   - ./cluster/lib/hazelcast-all-3.9.1.jar:/usr/local/tomcat/lib/hazelcast-all-3.9.1.jar
   - ./test-app/target/basic-web-app:/usr/local/tomcat/webapps/ROOT
   - ./cluster/logging.properties:/usr/local/tomcat/conf/logging.properties
tomcatThree:
  image: tomcat:7.0-jre8
  volumes:
   - ./cluster/hazelcast-server.xml:/usr/local/tomcat/conf/server.xml
   - ./cluster/hazelcast-context.xml:/usr/local/tomcat/conf/context.xml
   - ./cluster/lib/hazelcast-tomcat7-sessionmanager-1.1.3.jar:/usr/local/tomcat/lib/hazelcast-tomcat7-sessionmanager-1.1.3.jar
   # - ~/.m2/repository/com/hazelcast/hazelcast-tomcat7-sessionmanager/1.1.4-SNAPSHOT/hazelcast-tomcat7-sessionmanager-1.1.4-SNAPSHOT.jar:/usr/local/tomcat/lib/hazelcast-tomcat7-sessionmanager-1.1.4-SNAPSHOT.jar
   - ./cluster/lib/hazelcast-all-3.9.1.jar:/usr/local/tomcat/lib/hazelcast-all-3.9.1.jar
   - ./test-app/target/basic-web-app:/usr/local/tomcat/webapps/ROOT
   - ./cluster/logging.properties:/usr/local/tomcat/conf/logging.properties
